version: '3.8'

services:
  mongo:
    container_name: mongo
    image: mongodb-docker
    build: ./df_for_mongodb/
    volumes:
      - ./database_mongodb/data:/data/db
    ports:
      - 27017:27017
    restart: always